# Generated by Django 6.0.4 on 2026-04-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quality', models.CharField(help_text='যেমন গ্রেড / মান', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'stock_management_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailySell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, help_text='বিক্রয় মুহূর্তে পণ্যের দাম সংরক্ষণ', max_digits=12)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='stock.product')),
            ],
            options={
                'db_table': 'stock_management_dailysell',
                'ordering': ['-sold_at'],
            },
        ),
    ]
