# Generated by Django 6.0.4 on 2026-04-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysell',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='বাকি (মোট − পরিশোধ)', max_digits=12),
        ),
        migrations.AddField(
            model_name='dailysell',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ক্রেতা যে টাকা দিয়েছে', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='প্রতি এককের দাম (টাকা)। বিক্রয় মোট = একক দাম × পরিমাণ।', max_digits=12),
        ),
    ]
